---
title: "Literature Comparison"
author: "Shelly Trigg"
date: "3/23/2020"
output: github_document
editor_options: 
  chunk_output_type: console
---

load libraries
```{r}
library(readxl)
```

read in data
```{r}
## Literature data


#Dineshram GBC 2016 table 6
temp_prots <- read_xlsx("downloaded_published_data/gcb13249-sup-0003-tables4.xlsx", skip = 2)


#pediveliger specific proteins
inSil_prots <- read.csv("downloaded_published_data/2019_Foulon_etal_inSilTRX_Cgigas.csv", header = TRUE, stringsAsFactors = FALSE)


## Read in all proteins detected in proteomics and BLAST'd to Uniprot DB **for C.gigas**. Need the Uniprot IDs from this table for matching the temperature- and time-affected proteins to.

# I did this blast on roadrunner here: /home/srlab/Documents/Shelly/Cgigas/Cgiga-uniprot-blastP-out.tab 
### ran the following commands:
##### makeblastdb -in UP000005408_29159.fasta -out UNIPROT_Cgigas_db -dbtype prot
##### blastp -query Cg_Giga_cont_AA.fa -db UNIPROT_Cgigas_db -out Cgiga-uniprot-blastP-out.tab -num_threads 8 -max_hsps 1 -max_target_seqs 1 -outfmt 6
### all input and output can be found here: https://gannet.fish.washington.edu/metacarcinus/Cgigas/BLAST2gigas_uniprot/

tempxtime_prots <- read.csv("Cgiga-uniprot-blastP-out.tab", sep = "\t", header = FALSE, stringsAsFactors = FALSE)


## Read in ASCA-identified temperature- and time-affected proteins
ASCA_Temp_clade <- read.csv("../../SupplementalFiles/Supplemental_Table_5.csv", stringsAsFactors = FALSE)

ASCA_Time_clade <- read.csv("../../SupplementalFiles/Supplemental_Table_4.csv", stringsAsFactors = FALSE)

PCA_d21d27_clade <- read.csv("../../SupplementalFiles/Supplemental_Table_3.csv", stringsAsFactors = FALSE)
```

format data
```{r}

#change column name to match all dfs
colnames(tempxtime_prots)[1] <- "protein_ID"

colnames(ASCA_Temp_clade)[1] <- "protein_ID"
colnames(temp_prots)[3] <- "UniprotID"

#replace '|' with '.' and '-' with '.' in protein ID column of tempxtime_prots df
tempxtime_prots$protein_ID <- gsub("\\|","\\.", tempxtime_prots$protein_ID)
tempxtime_prots$protein_ID <- gsub("-","\\.", tempxtime_prots$protein_ID)
#replace 'tr|' with nothing in UniprotID column
tempxtime_prots$V2 <- gsub("tr\\|","", tempxtime_prots$V2)

#format column 2 to uniprot ID and entry name columns
tempxtime_prots$UniprotID <- gsub("\\|.*","", tempxtime_prots$V2)
tempxtime_prots$Entry_name <- gsub(".*\\|","", tempxtime_prots$V2)

#filter for proteins with low evalue
tempxtime_prots <- tempxtime_prots[which(tempxtime_prots$V11 <= 1 * 10^(-10)),]






```



merge Uniprot data with proteome data
```{r}

#merge ASCA data with Uniprot data
ASCA_Temp_clade <- merge(ASCA_Temp_clade[which(ASCA_Temp_clade$ASCA_PC_threshold_pass=="Yes"),], tempxtime_prots[,c("protein_ID", "UniprotID", "Entry_name")], by = "protein_ID")

ASCA_Time_clade <- merge(ASCA_Time_clade[which(ASCA_Time_clade$ASCA_PC_threshold_pass=="Yes"),], tempxtime_prots[,c("protein_ID", "UniprotID", "Entry_name")], by = "protein_ID")

PCA_d21d27_clade <- merge(PCA_d21d27_clade[which(PCA_d21d27_clade$PC_threshold_pass=="Yes"),], tempxtime_prots[,c("protein_ID", "UniprotID", "Entry_name")], by = "protein_ID")



```


check overlap in ASCA temperature-affected proteins
```{r}


# compare Dineshram temp affected proteins with ASCA temp affected proteins
ASCA_temp_Dineshram_temp_common <- merge(ASCA_Temp_clade[which(ASCA_Temp_clade$ASCA_PC_threshold_pass=="Yes"),], temp_prots[,c(1,3:4,grep("Average:T", colnames(temp_prots)))], by = "UniprotID")

nrow(ASCA_temp_Dineshram_temp_common)

#threshold for proteins that were more highly expressed at high temperature
ASCA_temp_Dineshram_temp_common_1.2x <- ASCA_temp_Dineshram_temp_common[ASCA_temp_Dineshram_temp_common[,16]>=1.2|ASCA_temp_Dineshram_temp_common[,17]>=1.2|ASCA_temp_Dineshram_temp_common[,18]>=1.2|ASCA_temp_Dineshram_temp_common[,19]>=1.2,]


#print the number of overlapping proteins that show increased abundance at 29C in our experiment
nrow(ASCA_temp_Dineshram_temp_common_1.2x[which(ASCA_temp_Dineshram_temp_common_1.2x$ClusterColor == "darkorange3"),])

ASCA_temp_Dineshram_temp_common_1.2x[which(ASCA_temp_Dineshram_temp_common_1.2x$ClusterColor == "darkorange3"),c("protein_ID", "UniprotID", "Accession no.", "Protein_names")]
```


check overlap in ASCA time-affected proteins
```{r}
ASCA_time_inSil <- merge(ASCA_Time_clade[which(ASCA_Time_clade$ASCA_PC_threshold_pass=="Yes"),], inSil_prots, by = "UniprotID")
nrow(ASCA_time_inSil)
ASCA_time_inSil



ASCA_temp_inSil <- merge(ASCA_Temp_clade[which(ASCA_Temp_clade$ASCA_PC_threshold_pass=="Yes"),], inSil_prots, by = "UniprotID")
nrow(ASCA_temp_inSil)

PCA_inSil <- merge(PCA_d21d27_clade[which(PCA_d21d27_clade$ASCA_PC_threshold_pass=="Yes"),], inSil_prots, by = "UniprotID")

nrow(PCA_inSil)
```





